--
-- PostgreSQL database dump
--

\restrict 5xf6ajqZpWyabqMml5B8h4LWbwt8jHDlU0j2ZtajiMuaEC7of7bsEZ2PR03qimq

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: update_timestamp(); Type: FUNCTION; Schema: public; Owner: rta_user
--

CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_timestamp() OWNER TO rta_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.audit_logs (
    audit_id integer NOT NULL,
    user_id integer,
    action character varying(100) NOT NULL,
    table_name character varying(50) NOT NULL,
    record_id integer,
    old_value jsonb,
    new_value jsonb,
    ip_address character varying(50),
    action_time timestamp without time zone DEFAULT now()
);


ALTER TABLE public.audit_logs OWNER TO rta_user;

--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.audit_logs_audit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.audit_logs_audit_id_seq OWNER TO rta_user;

--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.audit_logs_audit_id_seq OWNED BY public.audit_logs.audit_id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO rta_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO rta_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO rta_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO rta_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO rta_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO rta_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_statements; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.bank_statements (
    bank_stmt_id integer NOT NULL,
    bank_name character varying(100) NOT NULL,
    account_no character varying(50) NOT NULL,
    statement_from date NOT NULL,
    statement_to date NOT NULL,
    uploaded_by_id integer,
    uploaded_at timestamp without time zone DEFAULT now(),
    file_name character varying(255),
    total_debit numeric(15,2) DEFAULT 0,
    total_credit numeric(15,2) DEFAULT 0
);


ALTER TABLE public.bank_statements OWNER TO rta_user;

--
-- Name: bank_statements_bank_stmt_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.bank_statements_bank_stmt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bank_statements_bank_stmt_id_seq OWNER TO rta_user;

--
-- Name: bank_statements_bank_stmt_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.bank_statements_bank_stmt_id_seq OWNED BY public.bank_statements.bank_stmt_id;


--
-- Name: bank_transactions; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.bank_transactions (
    bank_txn_id integer NOT NULL,
    bank_stmt_id integer,
    txn_date date NOT NULL,
    reference_no character varying(100),
    debit numeric(15,2) DEFAULT 0,
    credit numeric(15,2) DEFAULT 0,
    balance numeric(15,2),
    description text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.bank_transactions OWNER TO rta_user;

--
-- Name: bank_transactions_bank_txn_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.bank_transactions_bank_txn_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bank_transactions_bank_txn_id_seq OWNER TO rta_user;

--
-- Name: bank_transactions_bank_txn_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.bank_transactions_bank_txn_id_seq OWNED BY public.bank_transactions.bank_txn_id;


--
-- Name: clients; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.clients (
    client_id integer NOT NULL,
    client_code character varying(20) NOT NULL,
    full_name character varying(200) NOT NULL,
    boid character varying(50),
    holder_type character varying(50),
    pan_or_citizenship character varying(50),
    bank_account_no character varying(50),
    bank_name character varying(100),
    status character varying(10) DEFAULT 'Active'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    company_id integer,
    CONSTRAINT clients_holder_type_check CHECK (((holder_type)::text = ANY ((ARRAY['Public'::character varying, 'Promoter'::character varying, 'Institution'::character varying])::text[]))),
    CONSTRAINT clients_status_check CHECK (((status)::text = ANY ((ARRAY['Active'::character varying, 'Inactive'::character varying])::text[])))
);


ALTER TABLE public.clients OWNER TO rta_user;

--
-- Name: clients_client_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.clients_client_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.clients_client_id_seq OWNER TO rta_user;

--
-- Name: clients_client_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.clients_client_id_seq OWNED BY public.clients.client_id;


--
-- Name: companies; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.companies (
    company_id integer NOT NULL,
    company_code character varying(20) NOT NULL,
    company_name character varying(200) NOT NULL,
    sector_type character varying(50),
    interest_tax_status character varying(50),
    pan_no character varying(50),
    bank_account_no character varying(50),
    bank_name character varying(100),
    status character varying(10) DEFAULT 'Active'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT companies_interest_tax_status_check CHECK (((interest_tax_status)::text = ANY ((ARRAY['Taxable'::character varying, 'Exempted'::character varying])::text[]))),
    CONSTRAINT companies_sector_type_check CHECK (((sector_type)::text = ANY ((ARRAY['Public'::character varying, 'Private'::character varying])::text[]))),
    CONSTRAINT companies_status_check CHECK (((status)::text = ANY ((ARRAY['Active'::character varying, 'Inactive'::character varying])::text[])))
);


ALTER TABLE public.companies OWNER TO rta_user;

--
-- Name: companies_company_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.companies_company_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.companies_company_id_seq OWNER TO rta_user;

--
-- Name: companies_company_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.companies_company_id_seq OWNED BY public.companies.company_id;


--
-- Name: dividend_payables; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.dividend_payables (
    dividend_id integer NOT NULL,
    company_id integer,
    client_id integer,
    shares_held numeric(15,2),
    gross_dividend numeric(15,2),
    tax_amount numeric(15,2) DEFAULT 0,
    net_payable numeric(15,2),
    payment_status character varying(20) DEFAULT 'Pending'::character varying,
    payment_date date,
    payment_reference character varying(100),
    fiscal_year character varying(20),
    created_by_id integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT dividend_payables_gross_dividend_check CHECK ((gross_dividend >= (0)::numeric)),
    CONSTRAINT dividend_payables_net_payable_check CHECK ((net_payable >= (0)::numeric)),
    CONSTRAINT dividend_payables_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['Pending'::character varying, 'Paid'::character varying, 'Partial'::character varying])::text[]))),
    CONSTRAINT dividend_payables_shares_held_check CHECK ((shares_held >= (0)::numeric)),
    CONSTRAINT dividend_payables_tax_amount_check CHECK ((tax_amount >= (0)::numeric))
);


ALTER TABLE public.dividend_payables OWNER TO rta_user;

--
-- Name: dividend_payables_dividend_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.dividend_payables_dividend_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.dividend_payables_dividend_id_seq OWNER TO rta_user;

--
-- Name: dividend_payables_dividend_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.dividend_payables_dividend_id_seq OWNED BY public.dividend_payables.dividend_id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO rta_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO rta_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO rta_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO rta_user;

--
-- Name: fiscal_year_settings; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.fiscal_year_settings (
    id integer NOT NULL,
    company_id integer NOT NULL,
    fiscal_year character varying(20) NOT NULL,
    interest_rate numeric(5,2) DEFAULT 7.00,
    tax_rate numeric(5,2) DEFAULT 0.00,
    is_active boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.fiscal_year_settings OWNER TO rta_user;

--
-- Name: fiscal_year_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.fiscal_year_settings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fiscal_year_settings_id_seq OWNER TO rta_user;

--
-- Name: fiscal_year_settings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.fiscal_year_settings_id_seq OWNED BY public.fiscal_year_settings.id;


--
-- Name: interest_payables; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.interest_payables (
    interest_id integer NOT NULL,
    company_id integer,
    client_id integer,
    instrument_ref character varying(100),
    gross_interest numeric(15,2) NOT NULL,
    tax_amount numeric(15,2) DEFAULT 0 NOT NULL,
    net_payable numeric(15,2) NOT NULL,
    due_date date NOT NULL,
    payment_status character varying(20) DEFAULT 'Pending'::character varying,
    payment_date date,
    payment_reference character varying(100),
    created_by_id integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    allotted_quantity integer,
    principal_amount numeric(15,2),
    interest_rate numeric(5,2),
    interest_per_day numeric(10,4),
    interest_pumori numeric(15,2),
    bank_code character varying(20),
    bank_name character varying(100),
    account_number character varying(50),
    lot character varying(50),
    approved_date date,
    tax_rate numeric(5,2),
    remarks text,
    tax_exempted boolean NOT NULL,
    CONSTRAINT interest_payables_gross_interest_check CHECK ((gross_interest >= (0)::numeric)),
    CONSTRAINT interest_payables_net_payable_check CHECK ((net_payable >= (0)::numeric)),
    CONSTRAINT interest_payables_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['Pending'::character varying, 'Paid'::character varying, 'Partial'::character varying])::text[]))),
    CONSTRAINT interest_payables_tax_amount_check CHECK ((tax_amount >= (0)::numeric))
);


ALTER TABLE public.interest_payables OWNER TO rta_user;

--
-- Name: interest_payables_interest_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.interest_payables_interest_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.interest_payables_interest_id_seq OWNER TO rta_user;

--
-- Name: interest_payables_interest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.interest_payables_interest_id_seq OWNED BY public.interest_payables.interest_id;


--
-- Name: reconciliation; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.reconciliation (
    recon_id integer NOT NULL,
    bank_txn_id integer,
    source_type character varying(50),
    source_id integer NOT NULL,
    matched_amount numeric(15,2) NOT NULL,
    recon_status character varying(20) DEFAULT 'Matched'::character varying,
    notes text,
    reconciled_by_id integer,
    reconciled_at timestamp without time zone DEFAULT now(),
    CONSTRAINT reconciliation_recon_status_check CHECK (((recon_status)::text = ANY ((ARRAY['Matched'::character varying, 'Partial'::character varying, 'Exception'::character varying])::text[]))),
    CONSTRAINT reconciliation_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['Interest'::character varying, 'Dividend'::character varying])::text[])))
);


ALTER TABLE public.reconciliation OWNER TO rta_user;

--
-- Name: reconciliation_recon_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.reconciliation_recon_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.reconciliation_recon_id_seq OWNER TO rta_user;

--
-- Name: reconciliation_recon_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.reconciliation_recon_id_seq OWNED BY public.reconciliation.recon_id;


--
-- Name: roles; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying(50) NOT NULL,
    permissions jsonb,
    description text,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.roles OWNER TO rta_user;

--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.roles_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.roles_role_id_seq OWNER TO rta_user;

--
-- Name: roles_role_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.roles_role_id_seq OWNED BY public.roles.role_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: rta_user
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    full_name character varying(200),
    email character varying(100),
    password_hash text NOT NULL,
    role_id integer,
    status character varying(10) DEFAULT 'Active'::character varying,
    last_login timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['Active'::character varying, 'Inactive'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO rta_user;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: rta_user
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_user_id_seq OWNER TO rta_user;

--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rta_user
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: vw_client_payables_summary; Type: VIEW; Schema: public; Owner: rta_user
--

CREATE VIEW public.vw_client_payables_summary AS
 SELECT cl.client_id,
    cl.client_code,
    cl.full_name,
    cl.holder_type,
    count(DISTINCT ip.interest_id) AS interest_count,
    count(DISTINCT dp.dividend_id) AS dividend_count,
    COALESCE(sum(ip.net_payable), (0)::numeric) AS total_interest,
    COALESCE(sum(dp.net_payable), (0)::numeric) AS total_dividend,
    (COALESCE(sum(ip.net_payable), (0)::numeric) + COALESCE(sum(dp.net_payable), (0)::numeric)) AS total_payable
   FROM ((public.clients cl
     LEFT JOIN public.interest_payables ip ON ((cl.client_id = ip.client_id)))
     LEFT JOIN public.dividend_payables dp ON ((cl.client_id = dp.client_id)))
  GROUP BY cl.client_id, cl.client_code, cl.full_name, cl.holder_type;


ALTER TABLE public.vw_client_payables_summary OWNER TO rta_user;

--
-- Name: vw_dividend_summary_by_company; Type: VIEW; Schema: public; Owner: rta_user
--

CREATE VIEW public.vw_dividend_summary_by_company AS
 SELECT c.company_id,
    c.company_code,
    c.company_name,
    count(dp.dividend_id) AS total_records,
    sum(dp.shares_held) AS total_shares,
    sum(dp.gross_dividend) AS total_gross,
    sum(dp.tax_amount) AS total_tax,
    sum(dp.net_payable) AS total_net,
    sum(
        CASE
            WHEN ((dp.payment_status)::text = 'Paid'::text) THEN dp.net_payable
            ELSE (0)::numeric
        END) AS paid_amount,
    sum(
        CASE
            WHEN ((dp.payment_status)::text = 'Pending'::text) THEN dp.net_payable
            ELSE (0)::numeric
        END) AS pending_amount
   FROM (public.companies c
     LEFT JOIN public.dividend_payables dp ON ((c.company_id = dp.company_id)))
  GROUP BY c.company_id, c.company_code, c.company_name;


ALTER TABLE public.vw_dividend_summary_by_company OWNER TO rta_user;

--
-- Name: vw_interest_summary_by_company; Type: VIEW; Schema: public; Owner: rta_user
--

CREATE VIEW public.vw_interest_summary_by_company AS
 SELECT c.company_id,
    c.company_code,
    c.company_name,
    c.sector_type,
    count(ip.interest_id) AS total_records,
    sum(ip.gross_interest) AS total_gross,
    sum(ip.tax_amount) AS total_tax,
    sum(ip.net_payable) AS total_net,
    sum(
        CASE
            WHEN ((ip.payment_status)::text = 'Paid'::text) THEN ip.net_payable
            ELSE (0)::numeric
        END) AS paid_amount,
    sum(
        CASE
            WHEN ((ip.payment_status)::text = 'Pending'::text) THEN ip.net_payable
            ELSE (0)::numeric
        END) AS pending_amount
   FROM (public.companies c
     LEFT JOIN public.interest_payables ip ON ((c.company_id = ip.company_id)))
  GROUP BY c.company_id, c.company_code, c.company_name, c.sector_type;


ALTER TABLE public.vw_interest_summary_by_company OWNER TO rta_user;

--
-- Name: audit_logs audit_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.audit_logs ALTER COLUMN audit_id SET DEFAULT nextval('public.audit_logs_audit_id_seq'::regclass);


--
-- Name: bank_statements bank_stmt_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_statements ALTER COLUMN bank_stmt_id SET DEFAULT nextval('public.bank_statements_bank_stmt_id_seq'::regclass);


--
-- Name: bank_transactions bank_txn_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_transactions ALTER COLUMN bank_txn_id SET DEFAULT nextval('public.bank_transactions_bank_txn_id_seq'::regclass);


--
-- Name: clients client_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.clients ALTER COLUMN client_id SET DEFAULT nextval('public.clients_client_id_seq'::regclass);


--
-- Name: companies company_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.companies ALTER COLUMN company_id SET DEFAULT nextval('public.companies_company_id_seq'::regclass);


--
-- Name: dividend_payables dividend_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.dividend_payables ALTER COLUMN dividend_id SET DEFAULT nextval('public.dividend_payables_dividend_id_seq'::regclass);


--
-- Name: fiscal_year_settings id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.fiscal_year_settings ALTER COLUMN id SET DEFAULT nextval('public.fiscal_year_settings_id_seq'::regclass);


--
-- Name: interest_payables interest_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.interest_payables ALTER COLUMN interest_id SET DEFAULT nextval('public.interest_payables_interest_id_seq'::regclass);


--
-- Name: reconciliation recon_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.reconciliation ALTER COLUMN recon_id SET DEFAULT nextval('public.reconciliation_recon_id_seq'::regclass);


--
-- Name: roles role_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.roles ALTER COLUMN role_id SET DEFAULT nextval('public.roles_role_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.audit_logs (audit_id, user_id, action, table_name, record_id, old_value, new_value, ip_address, action_time) FROM stdin;
1	1	Seed Companies	companies	0	\N	{"codes": ["NTC", "NABIL", "NRIC", "HIDCL", "NYADI", "SBL", "PRVU", "UNL", "NRCS", "NHPC", "CNRM"], "count": 11}	\N	2026-02-09 08:46:30.471737
2	1	Seed Clients	clients	0	\N	{"count": 9}	\N	2026-02-09 08:46:30.47949
3	1	Seed Payables	payables	0	\N	{"dividend": 12, "interest": 20}	\N	2026-02-09 08:46:30.484956
4	1	Seed Reconciliations	reconciliation	0	\N	{"bank_statements": 5}	\N	2026-02-09 08:46:30.49107
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add company	7	add_company
26	Can change company	7	change_company
27	Can delete company	7	delete_company
28	Can view company	7	view_company
29	Can add client	8	add_client
30	Can change client	8	change_client
31	Can delete client	8	delete_client
32	Can view client	8	view_client
33	Can add role	9	add_role
34	Can change role	9	change_role
35	Can delete role	9	delete_role
36	Can view role	9	view_role
37	Can add user	10	add_user
38	Can change user	10	change_user
39	Can delete user	10	delete_user
40	Can view user	10	view_user
41	Can add pending user change	11	add_pendinguserchange
42	Can change pending user change	11	change_pendinguserchange
43	Can delete pending user change	11	delete_pendinguserchange
44	Can view pending user change	11	view_pendinguserchange
45	Can add interest payable	12	add_interestpayable
46	Can change interest payable	12	change_interestpayable
47	Can delete interest payable	12	delete_interestpayable
48	Can view interest payable	12	view_interestpayable
49	Can add dividend payable	13	add_dividendpayable
50	Can change dividend payable	13	change_dividendpayable
51	Can delete dividend payable	13	delete_dividendpayable
52	Can view dividend payable	13	view_dividendpayable
53	Can add bank statement	14	add_bankstatement
54	Can change bank statement	14	change_bankstatement
55	Can delete bank statement	14	delete_bankstatement
56	Can view bank statement	14	view_bankstatement
57	Can add bank transaction	15	add_banktransaction
58	Can change bank transaction	15	change_banktransaction
59	Can delete bank transaction	15	delete_banktransaction
60	Can view bank transaction	15	view_banktransaction
61	Can add reconciliation	16	add_reconciliation
62	Can change reconciliation	16	change_reconciliation
63	Can delete reconciliation	16	delete_reconciliation
64	Can view reconciliation	16	view_reconciliation
65	Can add audit log	17	add_auditlog
66	Can change audit log	17	change_auditlog
67	Can delete audit log	17	delete_auditlog
68	Can view audit log	17	view_auditlog
69	Can add Fiscal Year Setting	18	add_fiscalyearsettings
70	Can change Fiscal Year Setting	18	change_fiscalyearsettings
71	Can delete Fiscal Year Setting	18	delete_fiscalyearsettings
72	Can view Fiscal Year Setting	18	view_fiscalyearsettings
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: bank_statements; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.bank_statements (bank_stmt_id, bank_name, account_no, statement_from, statement_to, uploaded_by_id, uploaded_at, file_name, total_debit, total_credit) FROM stdin;
1	Nepal Bank Limited	01001000012345	2026-01-10	2026-02-09	1	2026-02-09 08:46:30.204059	sample_nepal_bank.csv	1500.00	628750.00
2	Nabil Bank Limited	00405010010001	2026-01-15	2026-02-08	1	2026-02-09 08:46:30.274042	sample_nabil_bank.csv	0.00	495850.00
3	Nepal Rastra Bank	22010010000011	2025-12-31	2026-02-04	1	2026-02-09 08:46:30.327196	sample_nrb.csv	0.00	742400.00
4	Sunrise Bank Limited	03030300004567	2026-01-20	2026-02-14	1	2026-02-09 08:46:30.369117	sample_sunrise_bank.csv	2500.00	263200.00
5	Prabhu Bank Limited	05050500007890	2026-01-22	2026-02-12	1	2026-02-09 08:46:30.417337	sample_prabhu_bank.csv	0.00	387400.00
\.


--
-- Data for Name: bank_transactions; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.bank_transactions (bank_txn_id, bank_stmt_id, txn_date, reference_no, debit, credit, balance, description, created_at) FROM stdin;
1	1	2026-02-05	NB-INT-001	0.00	106250.00	2106250.00	Interest payout for NABIL-DB-2081-01	2026-02-09 08:46:30.21306
2	1	2026-02-06	NB-DIV-001	0.00	382500.00	2488750.00	Dividend payout NTC 2080/81	2026-02-09 08:46:30.227794
3	1	2026-02-07	NB-INT-002	0.00	50000.00	2538750.00	Part payment Nyadi debenture	2026-02-09 08:46:30.23988
4	1	2026-02-08	NB-DIV-002	0.00	90000.00	2628750.00	Dividend mismatch for NYADI	2026-02-09 08:46:30.252026
5	1	2026-02-09	NB-CHG-001	1500.00	0.00	2627250.00	Bank charges for RTS account	2026-02-09 08:46:30.263574
6	2	2026-01-30	NABIL-INT-001	0.00	127500.00	1800000.00	Interest settlement for NTC-DB-2080-03	2026-02-09 08:46:30.279757
7	2	2026-01-31	NABIL-DIV-001	0.00	234600.00	2034600.00	Dividend disbursement for KS0002	2026-02-09 08:46:30.292196
8	2	2026-02-01	NABIL-INT-002	0.00	70000.00	2104600.00	Partial payment for NABIL-DB-2080-07	2026-02-09 08:46:30.302023
9	2	2026-02-02	NABIL-DIV-002	0.00	63750.00	2168350.00	Dividend for Dipesh Pradhan (NABIL)	2026-02-09 08:46:30.312875
10	3	2026-01-28	NRB-INT-001	0.00	54400.00	5023000.00	Interest payout for HIDCL-BOND-2079-08	2026-02-09 08:46:30.333032
11	3	2026-01-29	NRB-INT-002	0.00	88000.00	5111000.00	T-Bill interest for NRIC	2026-02-09 08:46:30.344487
12	3	2026-01-30	NRB-DIV-001	0.00	600000.00	5711000.00	Dividend settlement for NRIC	2026-02-09 08:46:30.35611
13	4	2026-02-03	SBL-INT-001	0.00	86700.00	1765000.00	Interest payout for SBL-DB-2080-10	2026-02-09 08:46:30.375915
14	4	2026-02-05	SBL-DIV-001	0.00	76500.00	1841500.00	Dividend payout SBL FY2080/81	2026-02-09 08:46:30.386861
15	4	2026-02-08	SBL-DIV-002	0.00	100000.00	1941500.00	Partial dividend for Himalayan Foundation	2026-02-09 08:46:30.397473
16	4	2026-02-11	SBL-CHG-001	2500.00	0.00	1939000.00	RTGS service charge	2026-02-09 08:46:30.407832
17	5	2026-02-04	PRVU-INT-001	0.00	62050.00	1320000.00	Partial payout for PRVU-DB-2080-12	2026-02-09 08:46:30.423084
18	5	2026-02-07	PRVU-INT-002	0.00	140250.00	1460250.00	Interest payout for PRVU-DB-2080-11	2026-02-09 08:46:30.434772
19	5	2026-02-08	PRVU-DIV-001	0.00	132600.00	1592850.00	Dividend to Bodhi Gurung	2026-02-09 08:46:30.445377
20	5	2026-02-09	PRVU-DIV-002	0.00	52500.00	1645350.00	Dividend installment for Dipesh Pradhan	2026-02-09 08:46:30.45514
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.clients (client_id, client_code, full_name, boid, holder_type, pan_or_citizenship, bank_account_no, bank_name, status, created_at, updated_at, company_id) FROM stdin;
1	DP0001	Dipesh Pradhan	BOID-DP0001	Public	303045601	01001000022334	Rastriya Banijya Bank	Active	2026-02-09 08:46:29.93459	2026-02-09 08:46:29.941678	\N
2	KS0002	Khadka Securities Pvt. Ltd	BOID-KS0002	Institution	500209901	00405010022222	Nabil Bank Limited	Active	2026-02-09 08:46:29.949785	2026-02-09 08:46:29.95527	\N
3	SS0003	Saraswati Shrestha	BOID-SS0003	Promoter	209988776	01001000055667	Nepal Bank Limited	Active	2026-02-09 08:46:29.958523	2026-02-09 08:46:29.963158	\N
4	NR0004	National Retirement Fund	BOID-NR0004	Institution	700123654	22010010000099	Nepal Rastra Bank	Active	2026-02-09 08:46:29.969463	2026-02-09 08:46:29.979747	\N
5	MB0005	Mukti Bhandari	BOID-MB0005	Public	105509933	250101000456789	NIC Asia Bank	Active	2026-02-09 08:46:29.984921	2026-02-09 08:46:29.989449	\N
6	LP0006	Lumbini Pension Trust	BOID-LP0006	Institution	808080123	190101000334455	Nepal Investment Bank	Active	2026-02-09 08:46:29.993399	2026-02-09 08:46:30.000316	\N
7	SB0007	Samir Bista	BOID-SB0007	Public	301010101	03030300006789	Sunrise Bank Limited	Active	2026-02-09 08:46:30.003388	2026-02-09 08:46:30.007184	\N
8	HF0008	Himalayan Foundation	BOID-HF0008	Institution	888777666	05050500004567	Prabhu Bank Limited	Active	2026-02-09 08:46:30.011188	2026-02-09 08:46:30.013702	\N
9	BG0009	Bodhi Gurung	130160015777842	Promoter	207707707	06060600001234	Standard Chartered Bank Nepal	Active	2026-02-08 15:31:30.018063	2026-02-11 08:31:35.160438	\N
10	CL1	Client 1	BOID1	\N	\N	\N	\N	Active	2026-02-27 06:42:32.463405	2026-02-27 06:42:32.46342	13
11	CL2	Client 2	BOID2	\N	\N	\N	\N	Active	2026-02-27 06:42:32.475216	2026-02-27 06:42:32.475245	14
12	CL3	Client 3	BOID3	\N	\N	\N	\N	Active	2026-02-27 06:42:32.479575	2026-02-27 06:42:32.47959	15
13	CL4	Client 4	BOID4	\N	\N	\N	\N	Active	2026-02-27 06:42:32.484646	2026-02-27 06:42:32.48466	12
14	CL5	Client 5	BOID5	\N	\N	\N	\N	Active	2026-02-27 06:42:32.48987	2026-02-27 06:42:32.489883	13
15	CL001	Sample Client 1	BOID-CL001	\N	\N	\N	\N	Active	2026-02-27 09:07:34.947445	2026-02-27 09:07:34.947457	18
16	CL002	Sample Client 2	BOID-CL002	\N	\N	\N	\N	Active	2026-02-27 09:07:34.953916	2026-02-27 09:07:34.953947	19
\.


--
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.companies (company_id, company_code, company_name, sector_type, interest_tax_status, pan_no, bank_account_no, bank_name, status, created_at, updated_at) FROM stdin;
1	NTC	Nepal Telecom Company Limited	Public	Taxable	302045701	01001000012345	Rastriya Banijya Bank	Active	2026-02-09 08:46:29.81952	2026-02-09 08:46:29.824163
3	NRIC	Nepal Reinsurance Company	Public	Exempted	303030303	22010010000011	Nepal Rastra Bank	Active	2026-02-09 08:46:29.835881	2026-02-09 08:46:29.841489
5	NYADI	Nyadi Hydropower Limited	Private	Taxable	777888999	250101000123456	NIC Asia Bank	Active	2026-02-09 08:46:29.853035	2026-02-09 08:46:29.859372
6	SBL	Sunrise Bank Limited	Public	Taxable	606070808	03030300004567	Sunrise Bank Limited	Active	2026-02-09 08:46:29.863752	2026-02-09 08:46:29.876311
7	PRVU	Prabhu Bank Debenture Unit	Public	Taxable	777666555	05050500007890	Prabhu Bank Limited	Active	2026-02-09 08:46:29.879885	2026-02-09 08:46:29.88491
8	UNL	Unilever Nepal Limited	Private	Taxable	404040404	06060600004567	Standard Chartered Bank Nepal	Active	2026-02-09 08:46:29.889373	2026-02-09 08:46:29.892742
9	NRCS	Nepal Red Cross Society	Public	Exempted	500123456	22010010000055	Nepal Rastra Bank	Active	2026-02-09 08:46:29.89631	2026-02-09 08:46:29.906491
10	NHPC	Nepal Health and Population Commission	Public	Exempted	600234567	01001000088899	Rastriya Banijya Bank	Active	2026-02-09 08:46:29.910912	2026-02-09 08:46:29.916003
4	HIDCL	Hydroelectric Investment & Development Company Ltd	Public	Taxable	606060606	04030000012345	Himalayan Bank Ltd	Active	2026-02-09 03:01:29.84539	2026-02-10 09:34:05.133441
11	CNRM	Central Natural Resources Management	Public	Exempted	700345678	01001000055555	Nepal Bank Limited	Active	2026-02-09 03:01:29.920749	2026-02-10 09:34:22.270932
2	NABIL	Nabil Debenture Holdings	Public	Taxable	500207701	00405010010001	Nabil Bank Limited	Active	2026-02-09 03:01:29.828101	2026-02-22 09:21:49.361837
12	PUB1	Public One	Public	\N	\N	\N	\N	Active	2026-02-27 06:42:32.43762	2026-02-27 06:42:32.43764
13	PRI1	Private One	Private	\N	\N	\N	\N	Active	2026-02-27 06:42:32.446614	2026-02-27 06:42:32.446629
14	PRI2	Private Two	Private	\N	\N	\N	\N	Active	2026-02-27 06:42:32.450801	2026-02-27 06:42:32.450817
15	PUB2	Public Two	Public	\N	\N	\N	\N	Active	2026-02-27 06:42:32.45545	2026-02-27 06:42:32.455468
16	C1	Comp1	Public	\N	\N	\N	\N	Active	2026-02-27 06:52:11.353345	2026-02-27 06:52:11.353366
17	C2	Comp2	Private	\N	\N	\N	\N	Active	2026-02-27 06:52:11.358753	2026-02-27 06:52:11.358767
18	COMP001	Company 1	\N	\N	\N	\N	\N	Active	2026-02-27 09:07:34.931718	2026-02-27 09:07:34.931741
19	COMP002	Company 2	\N	\N	\N	\N	\N	Active	2026-02-27 09:07:34.938283	2026-02-27 09:07:34.938296
\.


--
-- Data for Name: dividend_payables; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.dividend_payables (dividend_id, company_id, client_id, shares_held, gross_dividend, tax_amount, net_payable, payment_status, payment_date, payment_reference, fiscal_year, created_by_id, created_at, updated_at) FROM stdin;
1	1	1	1500.00	450000.00	67500.00	382500.00	Paid	2026-01-10	\N	2080/81	1	2026-02-09 08:46:30.138699	2026-02-09 08:46:30.138711
2	1	3	740.00	222000.00	33300.00	188700.00	Pending	\N	\N	2081/82	1	2026-02-09 08:46:30.144591	2026-02-09 08:46:30.144603
3	2	2	920.00	276000.00	41400.00	234600.00	Paid	2026-01-22	\N	2080/81	1	2026-02-09 08:46:30.150948	2026-02-09 08:46:30.150959
4	3	4	2000.00	600000.00	0.00	600000.00	Paid	2025-11-11	\N	2079/80	1	2026-02-09 08:46:30.156702	2026-02-09 08:46:30.156713
5	4	6	350.00	105000.00	15750.00	89250.00	Pending	\N	\N	2081/82	1	2026-02-09 08:46:30.161123	2026-02-09 08:46:30.161135
6	5	5	420.00	126000.00	18900.00	107100.00	Partial	2026-02-02	\N	2081/82	1	2026-02-09 08:46:30.166967	2026-02-09 08:46:30.166978
7	2	1	250.00	75000.00	11250.00	63750.00	Pending	\N	\N	2081/82	1	2026-02-09 08:46:30.171456	2026-02-09 08:46:30.171467
8	6	7	300.00	90000.00	13500.00	76500.00	Paid	2026-01-20	\N	2080/81	1	2026-02-09 08:46:30.176804	2026-02-09 08:46:30.176816
9	6	8	450.00	135000.00	20250.00	114750.00	Pending	\N	\N	2081/82	1	2026-02-09 08:46:30.183418	2026-02-09 08:46:30.18343
10	7	9	520.00	156000.00	23400.00	132600.00	Pending	\N	\N	2081/82	1	2026-02-09 08:46:30.188257	2026-02-09 08:46:30.188268
11	8	7	610.00	305000.00	45750.00	259250.00	Paid	2025-12-26	\N	2080/81	1	2026-02-09 08:46:30.192332	2026-02-09 08:46:30.192342
12	8	8	250.00	125000.00	18750.00	106250.00	Paid	2025-12-11	\N	2079/80	1	2026-02-09 08:46:30.196784	2026-02-09 08:46:30.196794
13	18	15	1000.00	50000.00	7500.00	42500.00	Paid	\N	\N	2080/81	12	2026-02-27 09:07:51.397312	2026-02-27 09:07:51.397332
14	19	16	2500.00	125000.00	18750.00	106250.00	Pending	\N	\N	2080/81	12	2026-02-27 09:07:51.414542	2026-02-27 09:07:51.414555
15	18	15	1000.00	50000.00	7500.00	42500.00	Paid	\N	\N	2080/81	12	2026-02-27 09:15:26.349721	2026-02-27 09:15:26.349781
16	19	16	2500.00	125000.00	18750.00	106250.00	Pending	\N	\N	2080/81	12	2026-02-27 09:15:26.370585	2026-02-27 09:15:26.370602
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	companies	company
8	clients	client
9	users	role
10	users	user
11	users	pendinguserchange
12	payables	interestpayable
13	payables	dividendpayable
14	reconciliation	bankstatement
15	reconciliation	banktransaction
16	reconciliation	reconciliation
17	audit	auditlog
18	settings	fiscalyearsettings
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
18	clients	0001_initial	2026-02-09 08:41:43.151476+00
19	clients	0002_add_boid_field	2026-02-09 08:41:43.157875+00
21	settings	0001_initial	2026-02-09 08:41:43.178584+00
22	settings	0002_fix_company_id	2026-02-09 08:41:43.183811+00
23	settings	0003_drop_fiscal_year_unique	2026-02-09 08:41:43.192195+00
24	contenttypes	0001_initial	2026-02-09 10:45:11.061059+00
25	auth	0001_initial	2026-02-09 10:45:11.294473+00
26	admin	0001_initial	2026-02-09 10:45:11.340532+00
27	admin	0002_logentry_remove_auto_add	2026-02-09 10:45:11.353749+00
28	admin	0003_logentry_add_action_flag_choices	2026-02-09 10:45:11.369728+00
29	contenttypes	0002_remove_content_type_name	2026-02-09 10:45:11.431774+00
30	auth	0002_alter_permission_name_max_length	2026-02-09 10:45:11.451913+00
31	auth	0003_alter_user_email_max_length	2026-02-09 10:45:11.46665+00
32	auth	0004_alter_user_username_opts	2026-02-09 10:45:11.484198+00
33	auth	0005_alter_user_last_login_null	2026-02-09 10:45:11.50498+00
34	auth	0006_require_contenttypes_0002	2026-02-09 10:45:11.520152+00
35	auth	0007_alter_validators_add_error_messages	2026-02-09 10:45:11.556284+00
36	auth	0008_alter_user_username_max_length	2026-02-09 10:45:11.610723+00
37	auth	0009_alter_user_last_name_max_length	2026-02-09 10:45:11.635712+00
38	auth	0010_alter_group_name_max_length	2026-02-09 10:45:11.669914+00
39	auth	0011_update_proxy_permissions	2026-02-09 10:45:11.696173+00
40	auth	0012_alter_user_first_name_max_length	2026-02-09 10:45:11.712406+00
41	sessions	0001_initial	2026-02-09 10:45:11.769412+00
42	payables	0001_initial	2026-02-22 06:43:17.663332+00
43	clients	0003_add_company_field	2026-02-22 08:22:43.992314+00
44	payables	0002_add_public_sector_fields	2026-02-26 09:18:02.999201+00
45	payables	0003_institution_fields	2026-02-26 09:27:56.813808+00
46	payables	0004_tax_exempted	2026-02-26 09:27:56.837399+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
vec8hs5wkureed5xpkkgw1sjo5bcj476	.eJyrVopPLC3JiC8tTi2Kz0xRslKyUNJBFktKTM5OzQNJpGQl5qXn6yXn55UUZSbpgZToQWWL9XzzU1JznKBqUQzISCzOAOpWqgUAG0AmVA:1vvrfx:K5XE1v2gS6Va1blkbmqD6CptyMZOj0w3XpjMGE_OD_s	2026-03-13 06:50:13.85554+00
\.


--
-- Data for Name: fiscal_year_settings; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.fiscal_year_settings (id, company_id, fiscal_year, interest_rate, tax_rate, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: interest_payables; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.interest_payables (interest_id, company_id, client_id, instrument_ref, gross_interest, tax_amount, net_payable, due_date, payment_status, payment_date, payment_reference, created_by_id, created_at, updated_at, allotted_quantity, principal_amount, interest_rate, interest_per_day, interest_pumori, bank_code, bank_name, account_number, lot, approved_date, tax_rate, remarks, tax_exempted) FROM stdin;
1	2	1	NABIL-DB-2081-01	125000.00	18750.00	106250.00	2026-02-21	Pending	\N	\N	1	2026-02-09 08:46:30.028387	2026-02-09 08:46:30.028398	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
2	1	3	NTC-DB-2080-03	150000.00	22500.00	127500.00	2026-01-25	Paid	2026-01-28	NEPALPAY/NTC-INT-001	1	2026-02-09 08:46:30.03488	2026-02-09 08:46:30.034891	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
3	4	2	HIDCL-BOND-2080-02	98000.00	14700.00	83300.00	2026-03-06	Pending	\N	\N	1	2026-02-09 08:46:30.04044	2026-02-09 08:46:30.040451	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
4	5	6	NYADI-LOAN-2079-04	76000.00	11400.00	64600.00	2026-02-14	Partial	2026-02-07	NYADI/TDS-2079	1	2026-02-09 08:46:30.04485	2026-02-09 08:46:30.044859	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
5	3	4	NRIC-TBILL-2081-05	88000.00	0.00	88000.00	2026-02-06	Paid	2026-02-08	NRIC/NEPALPAY/2081	1	2026-02-09 08:46:30.049979	2026-02-09 08:46:30.050004	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
6	1	5	NTC-DB-2081-06	54000.00	8100.00	45900.00	2026-03-16	Pending	\N	\N	1	2026-02-09 08:46:30.055958	2026-02-09 08:46:30.055969	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
7	2	2	NABIL-DB-2080-07	132000.00	19800.00	112200.00	2026-01-20	Partial	2026-02-04	SWIFT/NABIL/7701	1	2026-02-09 08:46:30.061135	2026-02-09 08:46:30.061145	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
8	4	1	HIDCL-BOND-2079-08	64000.00	9600.00	54400.00	2025-12-11	Paid	2025-12-16	HBL/CMS/7788	1	2026-02-09 08:46:30.066612	2026-02-09 08:46:30.066623	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
9	6	7	SBL-DB-2081-09	88000.00	13200.00	74800.00	2026-02-27	Pending	\N	\N	1	2026-02-09 08:46:30.072571	2026-02-09 08:46:30.072582	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
10	6	8	SBL-DB-2080-10	102000.00	15300.00	86700.00	2026-01-15	Paid	2026-01-18	SBL/NEPALPAY/2080	1	2026-02-09 08:46:30.07765	2026-02-09 08:46:30.07766	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
11	7	1	PRVU-DB-2080-11	165000.00	24750.00	140250.00	2026-02-16	Pending	\N	\N	1	2026-02-09 08:46:30.082751	2026-02-09 08:46:30.082761	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
12	7	9	PRVU-DB-2080-12	73000.00	10950.00	62050.00	2026-02-01	Partial	2026-02-05	PRVU/SWIFT/7782	1	2026-02-09 08:46:30.088062	2026-02-09 08:46:30.088087	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
13	8	8	UNL-CP-2081-13	56000.00	0.00	56000.00	2026-02-23	Pending	\N	\N	1	2026-02-09 08:46:30.093592	2026-02-09 08:46:30.093602	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
14	8	7	UNL-NCD-2080-14	47000.00	7050.00	39950.00	2025-12-31	Paid	2026-01-05	UNL/CMS/3344	1	2026-02-09 08:46:30.100273	2026-02-09 08:46:30.100285	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
15	9	1	NRCS-GRT-2081-15	45000.00	0.00	45000.00	2026-02-19	Pending	\N	\N	1	2026-02-09 08:46:30.10542	2026-02-09 08:46:30.105433	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
16	9	2	NRCS-GRANT-2080-16	62000.00	0.00	62000.00	2026-02-01	Paid	2026-02-04	NRCS/HUMANITARIAN/2080	1	2026-02-09 08:46:30.110518	2026-02-09 08:46:30.110528	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
17	10	6	NHPC-HEALTH-2081-17	75000.00	0.00	75000.00	2026-03-01	Pending	\N	\N	1	2026-02-09 08:46:30.114522	2026-02-09 08:46:30.114551	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
18	10	5	NHPC-PUBLIC-2080-18	55000.00	0.00	55000.00	2026-01-10	Paid	2026-01-15	NHPC/NATIONAL/2080	1	2026-02-09 08:46:30.119879	2026-02-09 08:46:30.119889	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
19	11	7	CNRM-ENV-2081-19	68000.00	0.00	68000.00	2026-02-24	Pending	\N	\N	1	2026-02-09 08:46:30.126074	2026-02-09 08:46:30.126084	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
20	11	8	CNRM-RESOURCE-2080-20	52000.00	0.00	52000.00	2026-01-28	Partial	2026-02-01	CNRM/CONSERVATION/2080	1	2026-02-09 08:46:30.130442	2026-02-09 08:46:30.130452	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
21	14	13	\N	1000.00	100.00	900.00	2023-08-01	Pending	\N	\N	\N	2026-02-27 06:42:32.494031	2026-02-27 06:42:32.494045	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
22	13	14	\N	1050.00	105.00	945.00	2023-08-02	Pending	\N	\N	\N	2026-02-27 06:42:32.504405	2026-02-27 06:42:32.504416	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
23	13	14	\N	1100.00	110.00	990.00	2023-08-03	Pending	\N	\N	\N	2026-02-27 06:42:32.507408	2026-02-27 06:42:32.507418	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
24	12	12	\N	1150.00	115.00	1035.00	2023-08-04	Pending	\N	\N	\N	2026-02-27 06:42:32.510485	2026-02-27 06:42:32.510496	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
25	14	13	\N	1200.00	120.00	1080.00	2023-08-05	Pending	\N	\N	\N	2026-02-27 06:42:32.513525	2026-02-27 06:42:32.513568	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
26	13	14	\N	1250.00	125.00	1125.00	2023-08-06	Pending	\N	\N	\N	2026-02-27 06:42:32.516961	2026-02-27 06:42:32.516972	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
27	14	13	\N	1300.00	130.00	1170.00	2023-08-07	Pending	\N	\N	\N	2026-02-27 06:42:32.519955	2026-02-27 06:42:32.519965	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
28	14	11	\N	1350.00	135.00	1215.00	2023-08-08	Pending	\N	\N	\N	2026-02-27 06:42:32.522606	2026-02-27 06:42:32.522617	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
29	14	11	\N	1400.00	140.00	1260.00	2023-08-09	Pending	\N	\N	\N	2026-02-27 06:42:32.526349	2026-02-27 06:42:32.52636	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
30	13	12	\N	1450.00	145.00	1305.00	2023-08-10	Pending	\N	\N	\N	2026-02-27 06:42:32.529069	2026-02-27 06:42:32.529079	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
31	13	10	\N	1500.00	150.00	1350.00	2023-08-11	Pending	\N	\N	\N	2026-02-27 06:42:32.531765	2026-02-27 06:42:32.531777	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
32	14	13	\N	1550.00	155.00	1395.00	2023-08-12	Pending	\N	\N	\N	2026-02-27 06:42:32.534735	2026-02-27 06:42:32.534778	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
33	14	14	\N	1600.00	160.00	1440.00	2023-08-13	Pending	\N	\N	\N	2026-02-27 06:42:32.537291	2026-02-27 06:42:32.537302	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
34	13	12	\N	1650.00	165.00	1485.00	2023-08-14	Pending	\N	\N	\N	2026-02-27 06:42:32.540053	2026-02-27 06:42:32.540064	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
35	15	10	\N	1700.00	170.00	1530.00	2023-08-15	Pending	\N	\N	\N	2026-02-27 06:42:32.54855	2026-02-27 06:42:32.54856	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
36	15	11	\N	1750.00	175.00	1575.00	2023-08-16	Pending	\N	\N	\N	2026-02-27 06:42:32.551617	2026-02-27 06:42:32.551627	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
37	13	11	\N	1800.00	180.00	1620.00	2023-08-17	Pending	\N	\N	\N	2026-02-27 06:42:32.55411	2026-02-27 06:42:32.55412	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
38	12	14	\N	1850.00	185.00	1665.00	2023-08-18	Pending	\N	\N	\N	2026-02-27 06:42:32.557119	2026-02-27 06:42:32.55713	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
39	14	13	\N	1900.00	190.00	1710.00	2023-08-19	Pending	\N	\N	\N	2026-02-27 06:42:32.560236	2026-02-27 06:42:32.560246	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
40	15	14	\N	1950.00	195.00	1755.00	2023-08-20	Pending	\N	\N	\N	2026-02-27 06:42:32.564301	2026-02-27 06:42:32.564313	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
41	16	10	\N	100000.00	10000.00	90000.00	2023-08-01	Paid	\N	\N	\N	2026-02-27 06:52:11.37322	2026-02-27 06:52:11.373234	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
42	16	10	\N	50000.00	5000.00	45000.00	2023-08-01	Pending	\N	\N	\N	2026-02-27 06:52:11.39378	2026-02-27 06:52:11.393793	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
43	17	11	\N	88000.00	0.00	88000.00	2023-08-01	Paid	\N	\N	\N	2026-02-27 06:52:11.419334	2026-02-27 06:52:11.419345	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
44	17	11	\N	76000.00	11400.00	64600.00	2023-08-01	Pending	\N	\N	\N	2026-02-27 06:52:11.434556	2026-02-27 06:52:11.43457	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	f
\.


--
-- Data for Name: reconciliation; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.reconciliation (recon_id, bank_txn_id, source_type, source_id, matched_amount, recon_status, notes, reconciled_by_id, reconciled_at) FROM stdin;
1	1	Interest	1	106250.00	Matched	Matched interest for Dipesh Pradhan	2	2026-02-09 08:46:30.222923
2	2	Dividend	1	382500.00	Matched	\N	2	2026-02-09 08:46:30.235205
3	3	Interest	4	50000.00	Partial	First installment received	2	2026-02-09 08:46:30.24678
4	4	Dividend	6	90000.00	Exception	Credit less than expected net	2	2026-02-09 08:46:30.259186
5	6	Interest	2	127500.00	Matched	\N	2	2026-02-09 08:46:30.287419
6	7	Dividend	3	234600.00	Matched	\N	2	2026-02-09 08:46:30.297615
7	8	Interest	7	70000.00	Partial	Awaiting second tranche	2	2026-02-09 08:46:30.309167
8	9	Dividend	7	63750.00	Matched	\N	2	2026-02-09 08:46:30.321667
9	10	Interest	8	54400.00	Matched	\N	2	2026-02-09 08:46:30.340234
10	11	Interest	5	88000.00	Matched	\N	2	2026-02-09 08:46:30.351194
11	12	Dividend	4	600000.00	Matched	\N	2	2026-02-09 08:46:30.362638
12	13	Interest	10	86700.00	Matched	\N	2	2026-02-09 08:46:30.382211
13	14	Dividend	8	76500.00	Matched	\N	2	2026-02-09 08:46:30.393589
14	15	Dividend	9	100000.00	Partial	Awaiting balance credit	2	2026-02-09 08:46:30.403845
15	17	Interest	12	62050.00	Partial	50% settlement posted	2	2026-02-09 08:46:30.430454
16	18	Interest	11	140250.00	Matched	\N	2	2026-02-09 08:46:30.441507
17	19	Dividend	10	132600.00	Matched	\N	2	2026-02-09 08:46:30.451746
18	20	Dividend	7	52500.00	Partial	\N	2	2026-02-09 08:46:30.46329
19	10	Interest	6	45900.00	Matched	\N	1	2026-03-12 09:10:36.368662
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.roles (role_id, role_name, permissions, description, created_at) FROM stdin;
2	Finance Operator	{"clients": ["read"], "reports": ["read", "export"], "companies": ["read"], "bank_statements": ["create", "read"], "dividend_payables": ["create", "read", "update"], "interest_payables": ["create", "read", "update"]}	Create and manage payables	2026-02-09 08:41:33.624013
3	Reconciliation Officer	{"clients": ["read"], "reports": ["read", "export"], "companies": ["read"], "reconciliation": ["create", "read", "update"], "bank_statements": ["read"], "dividend_payables": ["read"], "interest_payables": ["read"]}	Handle bank reconciliation	2026-02-09 08:41:33.624013
5	Report Viewer	{"reports": ["read", "export"]}	View and export reports only	2026-02-09 08:41:33.624013
6	Accountant	{"audit": ["read"], "users": [], "clients": ["read"], "reports": ["read"], "companies": ["read"], "reconciliation": ["create", "read", "update"], "dividend_payables": ["create", "read", "update"], "interest_payables": ["create", "read", "update"]}	Settlement accountant responsible for matching payables	2026-02-09 08:46:27.579512
4	Auditor	{"audit": ["read"], "users": ["read"], "clients": ["read"], "reports": ["read"], "companies": ["read"], "reconciliation": ["read"], "dividend_payables": ["read"], "interest_payables": ["read"]}	External auditor for Nepal RTS	2026-02-09 02:56:33.624013
7	Maker	{"audit": [], "users": [], "clients": ["create", "read", "update"], "reports": ["read"], "companies": ["create", "read", "update"], "reconciliation": ["read"], "dividend_payables": ["create", "read"], "interest_payables": ["create", "read"]}	Maker desk user (Lalitpur registrar office)	2026-02-09 08:46:27.59733
8	Checker	{"audit": ["read"], "users": [], "clients": ["read", "update"], "reports": ["read"], "companies": ["read", "update"], "reconciliation": ["read", "update"], "dividend_payables": ["read", "update"], "interest_payables": ["read", "update"]}	Checker desk approving maker entries	2026-02-09 08:46:27.603555
9	Viewer	{"audit": ["read"], "users": [], "clients": ["read"], "reports": ["read"], "companies": ["read"], "reconciliation": ["read"], "dividend_payables": ["read"], "interest_payables": ["read"]}	Read-only dashboard consumer	2026-02-09 08:46:27.609284
1	Admin	{"users": ["create", "read", "update", "delete"], "dividend_payables": ["create", "read", "update", "delete"], "interest_payables": ["create", "read", "update", "delete"]}	System administrator for Nepal RTA/RTS sample environment	2026-02-08 21:11:33.624013
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: rta_user
--

COPY public.users (user_id, username, full_name, email, password_hash, role_id, status, last_login, created_at, updated_at) FROM stdin;
2	accountant	Ledger Accountant - Kathmandu	accountant@rta.gov.np	pbkdf2_sha256$600000$6KsvVyyhI2RRQM9RcauFyu$6AjcsLbDIP06rvp/kSEK/gL2nA7GQ5d9+lLvtfLAkj8=	6	Active	\N	2026-02-09 08:46:27.951529	2026-02-09 08:46:28.37681
3	auditor	OAG Nepal Auditor	auditor@oagnepal.gov.np	pbkdf2_sha256$600000$to4GcM98VPG6F6HIhvOpOZ$H7TQUYbUaD9JzKPA2g+Hnd4G2DgzqPbgwtcnk4+t29I=	4	Active	\N	2026-02-09 08:46:28.381673	2026-02-09 08:46:28.721706
4	maker	Maker Desk Lalitpur	maker@rta.gov.np	pbkdf2_sha256$600000$9jrQKjF7zh4Qrj4mYzLkVb$BHeqOb8xKXB2iPPle3cLH89f9EF1iKK/c6rOS1abcjo=	7	Active	\N	2026-02-09 08:46:28.72518	2026-02-09 08:46:29.055035
5	checker	Checker Desk Kathmandu	checker@rta.gov.np	pbkdf2_sha256$600000$8k0HxxrovNeyBP6y0ZRFAo$0BNXipw4zSnxRn+kwLXVtf7lefeCw/9UQGFo/r1el6U=	8	Active	\N	2026-02-09 08:46:29.058523	2026-02-09 08:46:29.425486
6	analyst	Data Analyst Nepal RTS	analyst@rta.gov.np	pbkdf2_sha256$600000$qcLVA0wu1AyJuKj9M37KGy$T4hmRON+ptdztp1CA2oISxu6Y8El4WqMg3Q+fdUi5Co=	9	Active	\N	2026-02-09 08:46:29.430581	2026-02-09 08:46:29.811821
8	sumcheck	\N	\N	x	1	Active	2026-02-27 06:50:13.850273	2026-02-27 06:50:13.8124	2026-02-27 06:50:13.85088
9	apitest	\N	\N	x	1	Active	\N	2026-02-27 06:50:29.409297	2026-02-27 06:50:29.409357
10	apitest2	\N	\N	x	1	Active	\N	2026-02-27 06:53:52.132877	2026-02-27 06:53:52.132891
12	e2e_test	E2E Test	e2e_test@example.com	pbkdf2_sha256$600000$XymrTCl1gfyqFMFxL1nA8X$k7juIIlHpqJFInxcd5CcRv4Ay9+teuzlh6AknMEEek4=	1	Active	2026-02-27 09:15:26.20085	2026-02-26 15:43:45.041296	2026-02-27 09:15:26.259165
1	admin	Central RTA Admin	admin@rta.gov.np	pbkdf2_sha256$600000$b0Bf0NXx953E1Br5N1TwW6$2jw2dFqqR3xOodApVAHATdx0b1bOTqpP6BQ+3F9u2UY=	1	Active	2026-03-12 09:11:39.018683	2026-01-09 10:56:33.62661	2026-03-12 09:11:39.019617
7	Admin	Sudeep Das	sudeep.das@rbbmbl.com.np	pbkdf2_sha256$600000$23V8cohBuIdiq6C5NQUD49$f5cNYd9EHAi/tXkhmhxA6Jomu7/3ajU6T/+2D4BHCDY=	1	Active	\N	2026-02-21 05:40:20.890241	2026-03-01 07:26:38.7498
\.


--
-- Name: audit_logs_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.audit_logs_audit_id_seq', 4, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: bank_statements_bank_stmt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.bank_statements_bank_stmt_id_seq', 5, true);


--
-- Name: bank_transactions_bank_txn_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.bank_transactions_bank_txn_id_seq', 20, true);


--
-- Name: clients_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.clients_client_id_seq', 24, true);


--
-- Name: companies_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.companies_company_id_seq', 23, true);


--
-- Name: dividend_payables_dividend_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.dividend_payables_dividend_id_seq', 47, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 46, true);


--
-- Name: fiscal_year_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.fiscal_year_settings_id_seq', 1, false);


--
-- Name: interest_payables_interest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.interest_payables_interest_id_seq', 44, true);


--
-- Name: reconciliation_recon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.reconciliation_recon_id_seq', 19, true);


--
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 9, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: rta_user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 12, true);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: bank_statements bank_statements_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_statements
    ADD CONSTRAINT bank_statements_pkey PRIMARY KEY (bank_stmt_id);


--
-- Name: bank_transactions bank_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (bank_txn_id);


--
-- Name: clients clients_boid_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_boid_key UNIQUE (boid);


--
-- Name: clients clients_client_code_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_client_code_key UNIQUE (client_code);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id);


--
-- Name: companies companies_company_code_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_company_code_key UNIQUE (company_code);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (company_id);


--
-- Name: dividend_payables dividend_payables_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.dividend_payables
    ADD CONSTRAINT dividend_payables_pkey PRIMARY KEY (dividend_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: fiscal_year_settings fiscal_year_settings_company_id_fiscal_year_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.fiscal_year_settings
    ADD CONSTRAINT fiscal_year_settings_company_id_fiscal_year_key UNIQUE (company_id, fiscal_year);


--
-- Name: fiscal_year_settings fiscal_year_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.fiscal_year_settings
    ADD CONSTRAINT fiscal_year_settings_pkey PRIMARY KEY (id);


--
-- Name: interest_payables interest_payables_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.interest_payables
    ADD CONSTRAINT interest_payables_pkey PRIMARY KEY (interest_id);


--
-- Name: reconciliation reconciliation_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.reconciliation
    ADD CONSTRAINT reconciliation_pkey PRIMARY KEY (recon_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_audit_action; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_audit_action ON public.audit_logs USING btree (action);


--
-- Name: idx_audit_table; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_audit_table ON public.audit_logs USING btree (table_name);


--
-- Name: idx_audit_time; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_audit_time ON public.audit_logs USING btree (action_time);


--
-- Name: idx_audit_user; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_audit_user ON public.audit_logs USING btree (user_id);


--
-- Name: idx_bank_stmt_bank; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_bank_stmt_bank ON public.bank_statements USING btree (bank_name);


--
-- Name: idx_bank_stmt_dates; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_bank_stmt_dates ON public.bank_statements USING btree (statement_from, statement_to);


--
-- Name: idx_bank_txn_date; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_bank_txn_date ON public.bank_transactions USING btree (txn_date);


--
-- Name: idx_bank_txn_ref; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_bank_txn_ref ON public.bank_transactions USING btree (reference_no);


--
-- Name: idx_bank_txn_stmt; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_bank_txn_stmt ON public.bank_transactions USING btree (bank_stmt_id);


--
-- Name: idx_clients_code; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_clients_code ON public.clients USING btree (client_code);


--
-- Name: idx_clients_holder_type; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_clients_holder_type ON public.clients USING btree (holder_type);


--
-- Name: idx_clients_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_clients_status ON public.clients USING btree (status);


--
-- Name: idx_companies_code; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_companies_code ON public.companies USING btree (company_code);


--
-- Name: idx_companies_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_companies_status ON public.companies USING btree (status);


--
-- Name: idx_dividend_client; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_dividend_client ON public.dividend_payables USING btree (client_id);


--
-- Name: idx_dividend_company; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_dividend_company ON public.dividend_payables USING btree (company_id);


--
-- Name: idx_dividend_fiscal_year; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_dividend_fiscal_year ON public.dividend_payables USING btree (fiscal_year);


--
-- Name: idx_dividend_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_dividend_status ON public.dividend_payables USING btree (payment_status);


--
-- Name: idx_fiscal_year_settings_company; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_fiscal_year_settings_company ON public.fiscal_year_settings USING btree (company_id);


--
-- Name: idx_fiscal_year_settings_fiscal_year; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_fiscal_year_settings_fiscal_year ON public.fiscal_year_settings USING btree (fiscal_year);


--
-- Name: idx_interest_client; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_interest_client ON public.interest_payables USING btree (client_id);


--
-- Name: idx_interest_company; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_interest_company ON public.interest_payables USING btree (company_id);


--
-- Name: idx_interest_due_date; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_interest_due_date ON public.interest_payables USING btree (due_date);


--
-- Name: idx_interest_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_interest_status ON public.interest_payables USING btree (payment_status);


--
-- Name: idx_recon_bank_txn; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_recon_bank_txn ON public.reconciliation USING btree (bank_txn_id);


--
-- Name: idx_recon_source; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_recon_source ON public.reconciliation USING btree (source_type, source_id);


--
-- Name: idx_recon_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_recon_status ON public.reconciliation USING btree (recon_status);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_users_role ON public.users USING btree (role_id);


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: idx_users_username; Type: INDEX; Schema: public; Owner: rta_user
--

CREATE INDEX idx_users_username ON public.users USING btree (username);


--
-- Name: clients trg_clients_update; Type: TRIGGER; Schema: public; Owner: rta_user
--

CREATE TRIGGER trg_clients_update BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: companies trg_companies_update; Type: TRIGGER; Schema: public; Owner: rta_user
--

CREATE TRIGGER trg_companies_update BEFORE UPDATE ON public.companies FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: dividend_payables trg_dividend_update; Type: TRIGGER; Schema: public; Owner: rta_user
--

CREATE TRIGGER trg_dividend_update BEFORE UPDATE ON public.dividend_payables FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: interest_payables trg_interest_update; Type: TRIGGER; Schema: public; Owner: rta_user
--

CREATE TRIGGER trg_interest_update BEFORE UPDATE ON public.interest_payables FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: users trg_users_update; Type: TRIGGER; Schema: public; Owner: rta_user
--

CREATE TRIGGER trg_users_update BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();


--
-- Name: audit_logs audit_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_statements bank_statements_uploaded_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_statements
    ADD CONSTRAINT bank_statements_uploaded_by_id_fkey FOREIGN KEY (uploaded_by_id) REFERENCES public.users(user_id);


--
-- Name: bank_transactions bank_transactions_bank_stmt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_bank_stmt_id_fkey FOREIGN KEY (bank_stmt_id) REFERENCES public.bank_statements(bank_stmt_id) ON DELETE CASCADE;


--
-- Name: clients clients_company_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_company_id_fk FOREIGN KEY (company_id) REFERENCES public.companies(company_id) ON DELETE SET NULL;


--
-- Name: dividend_payables dividend_payables_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.dividend_payables
    ADD CONSTRAINT dividend_payables_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id) ON DELETE CASCADE;


--
-- Name: dividend_payables dividend_payables_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.dividend_payables
    ADD CONSTRAINT dividend_payables_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id) ON DELETE CASCADE;


--
-- Name: dividend_payables dividend_payables_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.dividend_payables
    ADD CONSTRAINT dividend_payables_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.users(user_id);


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fiscal_year_settings fiscal_year_settings_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.fiscal_year_settings
    ADD CONSTRAINT fiscal_year_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id) ON DELETE CASCADE;


--
-- Name: interest_payables interest_payables_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.interest_payables
    ADD CONSTRAINT interest_payables_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id) ON DELETE CASCADE;


--
-- Name: interest_payables interest_payables_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.interest_payables
    ADD CONSTRAINT interest_payables_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id) ON DELETE CASCADE;


--
-- Name: interest_payables interest_payables_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.interest_payables
    ADD CONSTRAINT interest_payables_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.users(user_id);


--
-- Name: reconciliation reconciliation_bank_txn_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.reconciliation
    ADD CONSTRAINT reconciliation_bank_txn_id_fkey FOREIGN KEY (bank_txn_id) REFERENCES public.bank_transactions(bank_txn_id) ON DELETE CASCADE;


--
-- Name: reconciliation reconciliation_reconciled_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.reconciliation
    ADD CONSTRAINT reconciliation_reconciled_by_id_fkey FOREIGN KEY (reconciled_by_id) REFERENCES public.users(user_id);


--
-- Name: users users_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rta_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict 5xf6ajqZpWyabqMml5B8h4LWbwt8jHDlU0j2ZtajiMuaEC7of7bsEZ2PR03qimq

