# Generated by Django 4.2.8 on 2026-05-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iafallocation',
            new_name='allocations_boid_ebfc07_idx',
            old_name='boid_category_idx',
        ),
        migrations.RenameIndex(
            model_name='iafallocation',
            new_name='allocations_upload__92bbaf_idx',
            old_name='upload_date_idx',
        ),
    ]
