# Generated by Django 4.2.8 on 2026-06-16
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('clients', '0004_remove_client_idx_clients_code_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPayable',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(db_index=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], db_index=True, default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_payables', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_payables', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interest_payables', to='users.user')),
            ],
            options={
                'db_table': 'interest_payables',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='DividendPayable',
            fields=[
                ('dividend_id', models.AutoField(primary_key=True, serialize=False)),
                ('shares_held', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_dividend', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], db_index=True, default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fiscal_year', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payables', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payables', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dividend_payables', to='users.user')),
            ],
            options={
                'db_table': 'dividend_payables',
                'ordering': ['-created_at'],
            },
        ),
    ]