# Generated by Django 4.2.8 on 2026-06-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status'),
        ('payables', '0006_add_physical_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebentureReconciliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(db_index=True, help_text='Company identifier e.g. RBBL', max_length=50)),
                ('company_name', models.CharField(help_text='Company full name', max_length=200)),
                ('report_title', models.CharField(blank=True, default='', max_length=300)),
                ('report_subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('sn', models.IntegerField()),
                ('boid', models.CharField(db_index=True, max_length=50)),
                ('applicant_name', models.CharField(max_length=300)),
                ('father_mother_name', models.CharField(blank=True, default='', max_length=300)),
                ('grandfather_spouse_name', models.CharField(blank=True, default='', max_length=300)),
                ('citizenship_number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_from', models.CharField(blank=True, default='', max_length=100)),
                ('alloted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_interest', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('daily_interest', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('period_interest', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('net_interest_payable', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('roundup', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(db_index=True, max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('lot', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('REJECT/SUCCESS', 'REJECT/SUCCESS'), ('REJECT', 'REJECT'), ('MERGER', 'MERGER'), ('NEW PENDING', 'NEW PENDING')], db_index=True, default='SUCCESS', max_length=30)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('period_days', models.IntegerField(default=74)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('upload_batch', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'debenture_reconciliation',
                'ordering': ['company_code', 'sn'],
                'indexes': [models.Index(fields=['company_code', 'status'], name='debenture_r_company_b26028_idx'), models.Index(fields=['company_code', 'lot'], name='debenture_r_company_955310_idx')],
            },
        ),
    ]
