# Generated by Django 4.2.8 on 2026-07-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0007_debenturereconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='debenturereconciliation',
            name='sector_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Institution', 'Institution'), ('Government', 'Government'), ('Other', 'Other')], db_index=True, default='Public', help_text='Public/Private/Institution/Government', max_length=20),
        ),
        migrations.AddField(
            model_name='debenturereconciliation',
            name='tax_status',
            field=models.CharField(choices=[('Taxable', 'Taxable'), ('Exempted', 'Tax Exempted')], db_index=True, default='Taxable', help_text='Taxable or Tax Exempted', max_length=20),
        ),
    ]
