# Generated by custom update: add initial migration with BOID
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('boid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('holder_type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Promoter', 'Promoter'), ('Institution', 'Institution')], max_length=50, null=True)),
                ('pan_or_citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['client_code'],
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_code'], name='idx_clients_code'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['holder_type'], name='idx_clients_holder_type'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='idx_clients_status'),
        ),
    ]
