# Generated by Django 4.2.8 on 2026-05-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_company_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='idx_clients_code',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_clients_holder_type',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_clients_status',
        ),
    ]
