# Generated by Django 4.2.8 on 2026-05-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('bank_stmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=50)),
                ('statement_from', models.DateField()),
                ('statement_to', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'bank_statements',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('bank_txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_stmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reconciliation.bankstatement')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['txn_date'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('recon_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('Interest', 'Interest'), ('Dividend', 'Dividend')], max_length=50)),
                ('source_id', models.IntegerField()),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recon_status', models.CharField(choices=[('Matched', 'Matched'), ('Partial', 'Partial'), ('Exception', 'Exception')], default='Matched', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='reconciliation.banktransaction')),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'reconciliation',
                'ordering': ['-reconciled_at'],
            },
        ),
    ]
