# Generated by Django 4.2.8 on 2026-05-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('settings', '0003_drop_fiscal_year_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='company',
            field=models.ForeignKey(help_text='Company for this fiscal year setting', on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_year_settings', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='fiscal_year',
            field=models.CharField(help_text='Fiscal year (e.g., 2080-81, 2081-82)', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Interest rate percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set as current active fiscal year'),
        ),
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage', max_digits=5),
        ),
    ]
