# Generated by Django 4.2.8 on 2026-05-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_fiscalyearsettings_company_and_more'),
    ]

    operations = [
    ]
